# Generated by Django 5.1.4 on 2025-01-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railway_assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainmodel",
            name="composition",
            field=models.CharField(
                choices=[
                    ("multiple_unit", "Multiple Unit"),
                    ("locomotive", "Locomotive"),
                ],
                default="multiple_unit",
            ),
        ),
    ]
