# Generated by Django 5.1.4 on 2025-01-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railway_assets", "0002_trainmodel_composition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="electrification_voltage",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="route",
            name="gauge",
            field=models.PositiveSmallIntegerField(default=1435),
        ),
        migrations.AlterField(
            model_name="route",
            name="max_speed",
            field=models.PositiveSmallIntegerField(default=160),
        ),
        migrations.AlterField(
            model_name="route",
            name="opening_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="opening_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="platforms",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="train",
            name="construction_year",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="train",
            name="kilometers_run",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="train",
            name="number",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="train",
            name="year_entered_service",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="trainmodel",
            name="gauge",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="trainmodel",
            name="max_speed",
            field=models.PositiveSmallIntegerField(default=160),
        ),
        migrations.AlterField(
            model_name="trainmodel",
            name="power_output",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="trainmodel",
            name="seats",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trainmodel",
            name="weight",
            field=models.PositiveIntegerField(),
        ),
    ]
