# Generated by Django 5.1.4 on 2025-01-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railway_assets", "0003_alter_route_electrification_voltage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="gauge",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="route",
            name="max_speed",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="station",
            name="platforms",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="trainmodel",
            name="max_speed",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
