# Generated by Django 5.1.4 on 2025-02-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railway_assets", "0004_alter_route_gauge_alter_route_max_speed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="main_station",
            field=models.BooleanField(),
        ),
    ]
