services:
  railwaymanager-backend:
    build:
      context: app
      dockerfile: Dockerfile
    env_file:
      - .docker/secret.env
      - .docker/pg_conf.env
      - .docker/superuser_conf.env
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - static_volume:/app/staticfiles/

  db:
    image: postgres:16.6-alpine3.21
    env_file:
      - .docker/pg_conf.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: unless-stopped

volumes:
  postgres-data:
  static_volume:
