services:
  backend-proxy:
    image: nginx:stable-alpine
    depends_on:
      - railwaymanager-backend
    restart: unless-stopped
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/ssl:ro
      - static_volume:/app/staticfiles/
    ports:
      - "80:80"
      - "443:443"
